"""Script to generate the analysis.ipynb notebook programmatically."""
import json
import pathlib


def md_cell(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [source],
    }


def code_cell(source):
    lines = source.split("\n")
    sourced = [l + "\n" for l in lines[:-1]] + [lines[-1]]
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": sourced,
    }


nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": [],
}

C = nb["cells"]

# ── Title ──────────────────────────────────────────────────────────────────
C.append(md_cell(
    "# Pharma Sales Force Effectiveness\n"
    "## Call Response Curve Modeling — Full Analysis\n\n"
    "**Decision Analytics Portfolio Project** | ZS Associates application\n\n"
    "This notebook walks through the complete analytical pipeline:\n"
    "EDA → Baseline OLS → Michaelis-Menten response curve → Mixed-effects model → "
    "Marginal ROI optimization → Segment recommendations\n\n"
    "Run from the `notebooks/` directory. All modeling code lives in `src/`."
))

# ── 0. Setup ───────────────────────────────────────────────────────────────
C.append(code_cell(
    "import sys, warnings\n"
    "sys.path.insert(0, \"..\")\n"
    "warnings.filterwarnings(\"ignore\")\n\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "import seaborn as sns\n"
    "from scipy.stats import probplot\n\n"
    "from src.modeling import (\n"
    "    baseline_ols, fit_response_curve, fit_mixed_lm,\n"
    "    compute_vif, residual_diagnostics\n"
    ")\n"
    "from src.optimization import (\n"
    "    marginal_rx_curve, optimal_call_frequency,\n"
    "    compute_segment_recommendations,\n"
    "    DEFAULT_COST_PER_CALL, DEFAULT_REVENUE_PER_RX\n"
    ")\n\n"
    "%matplotlib inline\n"
    "plt.rcParams[\"figure.dpi\"] = 120\n"
    "print(\"Libraries loaded successfully.\")"
))

# ── 1. Load Data ───────────────────────────────────────────────────────────
C.append(md_cell("---\n## 1. Load Simulated Data\n\n"
    "The dataset is generated by `data/simulate_data.py`. "
    "See that file for all simulation assumptions (Michaelis-Menten curve, "
    "territory random effects, specialty moderation, lognormal noise)."))

C.append(code_cell(
    "df = pd.read_csv(\"../outputs/panel_data.csv\")\n"
    "print(f\"Shape: {df.shape}\")\n"
    "print(f\"Columns: {list(df.columns)}\")\n"
    "df.head(8)"
))

C.append(code_cell(
    "# Summary statistics\n"
    "print(\"--- Numerical summary ---\")\n"
    "print(df[[\"monthly_call_count\", \"rx_volume\"]].describe().round(2).to_string())\n\n"
    "print(\"\\n--- Specialty counts ---\")\n"
    "print(df.groupby(\"doctor_specialty\")[\"doctor_id\"].nunique())\n\n"
    "print(f\"\\nCall range: {df['monthly_call_count'].min()}–{df['monthly_call_count'].max()}\")\n"
    "print(f\"Rx range:   {df['rx_volume'].min():.1f}–{df['rx_volume'].max():.1f}\")"
))

# ── 2. EDA ─────────────────────────────────────────────────────────────────
C.append(md_cell("---\n## 2. Exploratory Data Analysis\n\n"
    "### 2.1 Univariate Distributions"))

C.append(code_cell(
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n\n"
    "ax = axes[0]\n"
    "ax.hist(df[\"monthly_call_count\"], bins=range(1, 14),\n"
    "        color=\"#4A90D9\", edgecolor=\"white\", alpha=0.85)\n"
    "ax.set_xlabel(\"Monthly Call Count\")\n"
    "ax.set_ylabel(\"Frequency\")\n"
    "ax.set_title(\"Distribution of Monthly Calls per Doctor\")\n\n"
    "ax = axes[1]\n"
    "ax.hist(df[\"rx_volume\"], bins=40, color=\"#E05C5C\", edgecolor=\"white\", alpha=0.85)\n"
    "ax.set_xlabel(\"Rx Volume (scripts/month)\")\n"
    "ax.set_title(\"Distribution of Rx Volume (right-skewed)\")\n\n"
    "plt.suptitle(\"EDA: Univariate Distributions\", fontweight=\"bold\", y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

C.append(md_cell("### 2.2 Calls vs Rx by Specialty\n\n"
    "> **Key observation:** The mean Rx per call level follows a concave, "
    "saturating pattern — not a straight line. This visually motivates the "
    "Michaelis-Menten non-linear model."))

C.append(code_cell(
    "SPEC_COLORS = {\n"
    "    \"GP\": \"#4A90D9\", \"Cardiologist\": \"#E05C5C\",\n"
    "    \"Endocrinologist\": \"#50C878\", \"Neurologist\": \"#F5A623\"\n"
    "}\n\n"
    "fig, axes = plt.subplots(2, 2, figsize=(13, 8))\n"
    "axes = axes.flatten()\n"
    "rng2 = np.random.default_rng(0)\n\n"
    "for ax, (spec, color) in zip(axes, SPEC_COLORS.items()):\n"
    "    sub = df[df[\"doctor_specialty\"] == spec]\n"
    "    jitter = rng2.uniform(-0.25, 0.25, len(sub))\n"
    "    ax.scatter(sub[\"monthly_call_count\"] + jitter, sub[\"rx_volume\"],\n"
    "               alpha=0.12, s=8, color=color)\n"
    "    means = sub.groupby(\"monthly_call_count\")[\"rx_volume\"].mean().reset_index()\n"
    "    ax.plot(means[\"monthly_call_count\"], means[\"rx_volume\"],\n"
    "            \"o-\", color=color, linewidth=2, markersize=7, label=\"Mean Rx\")\n"
    "    ax.set_title(spec, fontweight=\"bold\")\n"
    "    ax.set_xlabel(\"Monthly Calls\")\n"
    "    ax.set_ylabel(\"Rx Volume\")\n"
    "    ax.legend(fontsize=8)\n\n"
    "plt.suptitle(\"Calls vs Rx by Specialty — Non-linearity Visible\",\n"
    "             fontsize=13, fontweight=\"bold\")\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

C.append(md_cell("### 2.3 Territory Heterogeneity\n\n"
    "Mean Rx varies substantially across territories even controlling for specialty mix. "
    "This between-territory variation is the primary motivation for the mixed-effects model."))

C.append(code_cell(
    "terr_means = df.groupby(\"territory_id\")[\"rx_volume\"].mean().sort_values()\n\n"
    "fig, ax = plt.subplots(figsize=(13, 4))\n"
    "ax.bar(range(len(terr_means)), terr_means.values, color=\"#4A90D9\", alpha=0.85)\n"
    "ax.axhline(terr_means.mean(), color=\"red\", linestyle=\"--\", label=\"Overall mean\")\n"
    "ax.set_xticks(range(len(terr_means)))\n"
    "ax.set_xticklabels(terr_means.index, rotation=45, ha=\"right\")\n"
    "ax.set_ylabel(\"Mean Rx / Doctor-Month\")\n"
    "ax.set_title(\"Territory-Level Mean Rx - Substantial Heterogeneity\", fontweight=\"bold\")\n"
    "ax.legend()\n"
    "plt.tight_layout()\n"
    "plt.show()\n\n"
    "print(f\"Territory Rx SD: {terr_means.std():.2f} | CV: {terr_means.std()/terr_means.mean():.1%}\")"
))

# ── 3. Baseline OLS ────────────────────────────────────────────────────────
C.append(md_cell("---\n## 3. Baseline Model: OLS Linear Regression\n\n"
    "**Deliberately naive** — establishes a reference and exposes misspecification.\n\n"
    "```\nRx ~ beta0 + beta1 * calls + epsilon\n```"))

C.append(code_cell(
    "ols_res = baseline_ols(df)\n"
    "print(f\"R-squared: {ols_res['rsq']:.4f}\")\n"
    "print(f\"AIC: {ols_res['aic']:.1f}\")\n"
    "print(f\"BIC: {ols_res['bic']:.1f}\")\n"
    "print()\n"
    "print(ols_res[\"model\"].summary())"
))

C.append(code_cell(
    "# Residual diagnostics for OLS\n"
    "fig = plt.figure(figsize=(14, 5))\n"
    "gs = gridspec.GridSpec(1, 3)\n\n"
    "# (a) Scatter + fit line\n"
    "ax1 = fig.add_subplot(gs[0])\n"
    "jitter = np.random.default_rng(1).uniform(-0.3, 0.3, len(df))\n"
    "ax1.scatter(df[\"monthly_call_count\"] + jitter, df[\"rx_volume\"],\n"
    "            alpha=0.1, s=5, color=\"#4A90D9\")\n"
    "x_line = np.linspace(1, 12, 100)\n"
    "coef = ols_res[\"model\"].params\n"
    "ax1.plot(x_line, coef[\"Intercept\"] + coef[\"monthly_call_count\"] * x_line,\n"
    "         \"r-\", linewidth=2.5, label=f\"OLS R2={ols_res['rsq']:.3f}\")\n"
    "ax1.set_xlabel(\"Monthly Calls\"); ax1.set_ylabel(\"Rx Volume\")\n"
    "ax1.set_title(\"OLS Fit\", fontweight=\"bold\"); ax1.legend()\n\n"
    "# (b) Residuals vs Fitted\n"
    "ax2 = fig.add_subplot(gs[1])\n"
    "ax2.scatter(ols_res[\"predictions\"], ols_res[\"residuals\"], alpha=0.15, s=5, color=\"#E05C5C\")\n"
    "ax2.axhline(0, color=\"black\")\n"
    "ax2.set_xlabel(\"Fitted Values\"); ax2.set_ylabel(\"Residuals\")\n"
    "ax2.set_title(\"Residuals vs Fitted\\n(Curvature + heteroscedasticity)\", fontweight=\"bold\")\n\n"
    "# (c) Q-Q plot\n"
    "ax3 = fig.add_subplot(gs[2])\n"
    "(osm, osr), (slope, intercept, r) = probplot(ols_res[\"residuals\"], dist=\"norm\")\n"
    "ax3.scatter(osm, osr, alpha=0.3, s=5, color=\"#50C878\")\n"
    "ax3.plot(osm, slope * np.array(osm) + intercept, \"r-\", linewidth=2)\n"
    "ax3.set_xlabel(\"Theoretical Quantiles\"); ax3.set_ylabel(\"Sample Quantiles\")\n"
    "ax3.set_title(\"Q-Q Plot\\n(Non-normal residuals)\", fontweight=\"bold\")\n\n"
    "fig.suptitle(f\"Baseline OLS Diagnostics | AIC={ols_res['aic']:.0f}\", fontweight=\"bold\")\n"
    "plt.tight_layout()\n"
    "plt.show()\n\n"
    "diag = residual_diagnostics(ols_res[\"residuals\"], ols_res[\"predictions\"])\n"
    "print(\"Diagnostic summary:\")\n"
    "for k, v in diag.items():\n"
    "    print(f\"  {k}: {v}\")"
))

# ── 4. MM Response Curve ───────────────────────────────────────────────────
C.append(md_cell("---\n## 4. Response Curve: Michaelis-Menten Model\n\n"
    "```\nRx(calls) = (Vmax x calls) / (Km + calls)\n```\n\n"
    "**Why Michaelis-Menten?**\n"
    "- Has a hard asymptote (`Vmax`) — the biological prescribing ceiling\n"
    "- `Km` is interpretable: calls at which Rx reaches half of Vmax\n"
    "- AIC/BIC improve substantially over OLS\n\n"
    "Fitted separately per doctor specialty using `scipy.optimize.curve_fit`."))

C.append(code_cell(
    "rc_res = fit_response_curve(df, group_col=\"doctor_specialty\")\n\n"
    "print(\"Fitted MM parameters:\")\n"
    "for spec, params in rc_res[\"params\"].items():\n"
    "    if params.get(\"converged\", True):\n"
    "        vmax, km = params[\"vmax\"], params[\"km\"]\n"
    "        vmax_ci, km_ci = params[\"vmax_ci\"], params[\"km_ci\"]\n"
    "        print(f\"  {spec:20s} Vmax={vmax:.1f} (95% CI: {vmax_ci[0]:.1f}-{vmax_ci[1]:.1f})  \"\n"
    "              f\"Km={km:.2f} (95% CI: {km_ci[0]:.2f}-{km_ci[1]:.2f})\")\n\n"
    "print(f\"\\nTotal AIC: {rc_res['aic']:.1f}  (vs OLS: {ols_res['aic']:.1f})\")\n"
    "print(f\"AIC improvement: {ols_res['aic'] - rc_res['aic']:.1f} points\")"
))

C.append(code_cell(
    "# Plot response curves per specialty\n"
    "fig, axes = plt.subplots(2, 2, figsize=(13, 8))\n"
    "axes = axes.flatten()\n"
    "calls_range = np.linspace(0.1, 12, 200)\n\n"
    "for ax, (spec, color) in zip(axes, SPEC_COLORS.items()):\n"
    "    sub = df[df[\"doctor_specialty\"] == spec]\n"
    "    params = rc_res[\"params\"][spec]\n"
    "    if not params.get(\"converged\", True):\n"
    "        continue\n"
    "    vmax, km = params[\"vmax\"], params[\"km\"]\n"
    "    fitted_curve = (vmax * calls_range) / (km + calls_range)\n\n"
    "    jitter = np.random.default_rng(2).uniform(-0.3, 0.3, len(sub))\n"
    "    ax.scatter(sub[\"monthly_call_count\"] + jitter, sub[\"rx_volume\"],\n"
    "               alpha=0.12, s=8, color=color)\n"
    "    ax.plot(calls_range, fitted_curve, \"-\", color=color, linewidth=2.5,\n"
    "            label=f\"MM fit: Vmax={vmax:.1f}, Km={km:.2f}\")\n\n"
    "    opt = optimal_call_frequency(vmax, km)\n"
    "    n_star, rx_star = opt[\"optimal_calls\"], opt[\"rx_at_optimal\"]\n"
    "    ax.axvline(n_star, color=\"black\", linewidth=1.5, linestyle=\"--\")\n"
    "    ax.scatter([n_star], [rx_star], color=\"black\", s=100, zorder=5,\n"
    "               label=f\"n* = {n_star} calls\")\n"
    "    ax.set_title(spec, fontweight=\"bold\")\n"
    "    ax.set_xlabel(\"Monthly Calls\")\n"
    "    ax.set_ylabel(\"Rx Volume\")\n"
    "    ax.legend(fontsize=8)\n\n"
    "plt.suptitle(\"Michaelis-Menten Response Curves by Specialty\",\n"
    "             fontsize=13, fontweight=\"bold\")\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ── 5. Mixed-Effects ──────────────────────────────────────────────────────
C.append(md_cell("---\n## 5. Mixed-Effects Model\n\n"
    "```\nlog(Rx+1) ~ beta_calls * log(calls) + beta_specialty + (1 | territory_id)\n```\n\n"
    "**Why mixed-effects?**\n"
    "- Doctors within a territory share unobserved factors (formulary, disease prevalence)\n"
    "- Ignoring cluster structure -> understated SE -> false confidence\n"
    "- Random intercepts by territory correctly partition between- vs within-territory variation\n\n"
    "> Note: AIC from this model is not directly comparable to OLS AIC because\n"
    "> the outcome is `log(Rx+1)`, not `Rx`. Compare within-model using residual plots."))

C.append(code_cell(
    "me_res = fit_mixed_lm(df)\n"
    "print(f\"Mixed LM AIC: {me_res['aic']:.1f}\")\n"
    "print(f\"Mixed LM BIC: {me_res['bic']:.1f}\")\n"
    "print()\n"
    "print(me_res[\"model\"].summary())"
))

C.append(code_cell(
    "# Diagnostic plots\n"
    "fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))\n\n"
    "ax = axes[0]\n"
    "ax.scatter(me_res[\"predictions\"], me_res[\"residuals\"], alpha=0.15, s=5, color=\"#4A90D9\")\n"
    "ax.axhline(0, color=\"black\")\n"
    "ax.set_xlabel(\"Fitted log(Rx)\"); ax.set_ylabel(\"Residuals\")\n"
    "ax.set_title(\"Residuals vs Fitted\", fontweight=\"bold\")\n\n"
    "ax = axes[1]\n"
    "(osm, osr), (slope, intercept, r) = probplot(me_res[\"residuals\"], dist=\"norm\")\n"
    "ax.scatter(osm, osr, alpha=0.3, s=5, color=\"#E05C5C\")\n"
    "ax.plot(osm, slope * np.array(osm) + intercept, \"r-\", linewidth=2)\n"
    "ax.set_xlabel(\"Theoretical Quantiles\"); ax.set_ylabel(\"Sample Quantiles\")\n"
    "ax.set_title(\"Q-Q Plot\", fontweight=\"bold\")\n\n"
    "ax = axes[2]\n"
    "re_vals = [v.iloc[0] for v in me_res[\"random_effects\"].values()]\n"
    "ax.hist(re_vals, bins=12, color=\"#50C878\", edgecolor=\"white\", alpha=0.9)\n"
    "ax.axvline(0, color=\"red\", linestyle=\"--\")\n"
    "ax.set_xlabel(\"Territory Random Intercept\")\n"
    "ax.set_title(\"Territory Random Effects Distribution\", fontweight=\"bold\")\n\n"
    "plt.suptitle(f\"Mixed-Effects Model Diagnostics | AIC={me_res['aic']:.0f}\", fontweight=\"bold\")\n"
    "plt.tight_layout()\n"
    "plt.show()\n\n"
    "# Residual diagnostics\n"
    "me_diag = residual_diagnostics(me_res[\"residuals\"], me_res[\"predictions\"])\n"
    "print(\"Mixed LM diagnostics:\")\n"
    "for k, v in me_diag.items():\n"
    "    print(f\"  {k}: {v}\")"
))

# ── 6. Model Comparison ────────────────────────────────────────────────────
C.append(md_cell("---\n## 6. Model Comparison\n\n"
    "Note: The MM curve and OLS AICs are directly comparable (same outcome = Rx_volume). "
    "The Mixed LM AIC is on log-Rx scale and **not** directly comparable to the other two — "
    "it should be evaluated on its own diagnostics and interpretive merits."))

C.append(code_cell(
    "models_list = [\"Baseline OLS\", \"MM Curve (per specialty)\", \"Mixed LM (log-linear)\"]\n"
    "aic_vals = [ols_res[\"aic\"], rc_res[\"aic\"], me_res[\"aic\"]]\n"
    "bic_vals = [ols_res[\"bic\"], rc_res[\"bic\"], me_res[\"bic\"]]\n\n"
    "comparison = pd.DataFrame({\"Model\": models_list, \"AIC\": aic_vals, \"BIC\": bic_vals})\n"
    "display(comparison)\n\n"
    "print(f\"AIC improvement (OLS -> MM): {ols_res['aic'] - rc_res['aic']:.1f} points\")\n"
    "print(f\"MM AIC improvement is {(ols_res['aic'] - rc_res['aic'])/ols_res['aic']*100:.1f}% reduction\")"
))

# ── 7. VIF Diagnostics ────────────────────────────────────────────────────
C.append(md_cell("---\n## 7. Diagnostics: VIF Check\n\n"
    "In the primary model (single predictor: calls), multicollinearity is not applicable. "
    "However, if polynomial terms or interaction terms were added, VIF would be critical. "
    "We demonstrate VIF on a two-predictor version as a best-practice illustration."))

C.append(code_cell(
    "df_vif = df[[\"monthly_call_count\"]].copy()\n"
    "df_vif[\"calls_squared\"] = df_vif[\"monthly_call_count\"] ** 2\n\n"
    "vif_df = compute_vif(df_vif, [\"monthly_call_count\", \"calls_squared\"])\n"
    "print(\"VIF analysis (calls + calls^2):\")\n"
    "print(vif_df.to_string(index=False))\n"
    "print()\n"
    "print(\"Interpretation:\")\n"
    "print(\"  VIF > 10  -> Severe multicollinearity\")\n"
    "print(\"  VIF > 5   -> Moderate, warrants investigation\")\n"
    "print(\"  This confirms why the MM parameterisation (non-linear in calls)\")\n"
    "print(\"  is preferable to polynomial regression -- avoids collinearity issues.\")"
))

# ── 8. Optimization ────────────────────────────────────────────────────────
C.append(md_cell("---\n## 8. Optimization: Marginal ROI Analysis\n\n"
    "**Economic assumptions (explicit):**\n"
    "- Cost per call = **$250** (IQVIA/ZS industry benchmark midpoint; range $200-$350)\n"
    "- Net revenue per Rx = **$150** (branded drug after payer rebates)\n\n"
    "The optimal call frequency `n*` is the highest call level where:\n"
    "```\nmarginal_Rx(n) x revenue_per_Rx >= cost_per_call\n```"))

C.append(code_cell(
    "# Show marginal curve for one segment in detail\n"
    "spec = \"Cardiologist\"\n"
    "params = rc_res[\"params\"][spec]\n"
    "vmax, km = params[\"vmax\"], params[\"km\"]\n\n"
    "curve = marginal_rx_curve(vmax, km)\n"
    "curve[\"marginal_rev\"] = curve[\"marginal_rx\"] * DEFAULT_REVENUE_PER_RX\n"
    "curve[\"profitable\"] = curve[\"marginal_rev\"] >= DEFAULT_COST_PER_CALL\n\n"
    "print(f\"{spec} marginal analysis (cost/call=${DEFAULT_COST_PER_CALL}, rev/Rx=${DEFAULT_REVENUE_PER_RX}):\")\n"
    "print(curve[curve[\"calls\"] > 0].to_string(index=False))"
))

C.append(code_cell(
    "# Optimal call frequency per specialty\n"
    "print(\"Optimal call frequency per specialty:\")\n"
    "print(f\"{'Specialty':20s} {'n*':>4} {'Rx at n*':>12} {'ROI at n*':>12}\")\n"
    "print(\"-\" * 52)\n"
    "for spec in SPEC_COLORS:\n"
    "    p = rc_res[\"params\"].get(spec, {})\n"
    "    if not p.get(\"converged\", True):\n"
    "        continue\n"
    "    opt = optimal_call_frequency(p[\"vmax\"], p[\"km\"],\n"
    "                                  cost_per_call=DEFAULT_COST_PER_CALL,\n"
    "                                  revenue_per_rx=DEFAULT_REVENUE_PER_RX)\n"
    "    print(f\"  {spec:20s} {opt['optimal_calls']:>4}  {opt['rx_at_optimal']:>10.1f}  {opt['roi_at_optimal']:>10.1%}\")"
))

C.append(code_cell(
    "# Marginal revenue charts (all specialties)\n"
    "fig, axes = plt.subplots(2, 2, figsize=(13, 8))\n"
    "axes = axes.flatten()\n\n"
    "for ax, (spec, color) in zip(axes, SPEC_COLORS.items()):\n"
    "    params = rc_res[\"params\"][spec]\n"
    "    if not params.get(\"converged\", True):\n"
    "        continue\n"
    "    vmax, km = params[\"vmax\"], params[\"km\"]\n"
    "    c = marginal_rx_curve(vmax, km)\n"
    "    c = c[c[\"calls\"] > 0].copy()\n"
    "    c[\"marginal_rev\"] = c[\"marginal_rx\"] * DEFAULT_REVENUE_PER_RX\n"
    "    opt = optimal_call_frequency(vmax, km)\n"
    "    n_star = opt[\"optimal_calls\"]\n\n"
    "    ax.bar(c[\"calls\"], c[\"marginal_rev\"], color=color, alpha=0.75)\n"
    "    ax.axhline(DEFAULT_COST_PER_CALL, color=\"black\", linewidth=2, linestyle=\"--\",\n"
    "               label=f\"Cost/call (${DEFAULT_COST_PER_CALL:.0f})\")\n"
    "    ax.axvline(n_star, color=\"red\", linewidth=2, label=f\"n* = {n_star}\")\n"
    "    ax.set_xlabel(\"Monthly Calls\")\n"
    "    ax.set_ylabel(\"Marginal Revenue ($)\")\n"
    "    ax.set_title(spec, fontweight=\"bold\")\n"
    "    ax.legend(fontsize=8)\n\n"
    "plt.suptitle(\"Marginal Revenue per Additional Call vs Cost per Call\",\n"
    "             fontsize=13, fontweight=\"bold\")\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ── 9. Recommendations ────────────────────────────────────────────────────
C.append(md_cell("---\n## 9. Segment Recommendation Table\n\n"
    "Final business output: segment-level call frequency recommendations with projected impact."))

C.append(code_cell(
    "converged_params = {\n"
    "    s: rc_res[\"params\"][s] for s in rc_res[\"params\"]\n"
    "    if rc_res[\"params\"][s].get(\"converged\", True)\n"
    "}\n\n"
    "reco = compute_segment_recommendations(\n"
    "    converged_params, df,\n"
    "    segment_col=\"doctor_specialty\",\n"
    "    cost_per_call=DEFAULT_COST_PER_CALL,\n"
    "    revenue_per_rx=DEFAULT_REVENUE_PER_RX,\n"
    ")\n"
    "display(reco)\n\n"
    "reco.to_csv(\"../outputs/segment_recommendations.csv\", index=False)\n"
    "print(\"Saved to ../outputs/segment_recommendations.csv\")"
))

C.append(code_cell(
    "# Summary narrative\n"
    "print(\"=\" * 60)\n"
    "print(\"SEGMENT-LEVEL CALL PLAN RECOMMENDATIONS\")\n"
    "print(f\"  Assumptions: ${DEFAULT_COST_PER_CALL}/call | ${DEFAULT_REVENUE_PER_RX}/Rx\")\n"
    "print(\"=\" * 60)\n"
    "for _, row in reco.iterrows():\n"
    "    action = row[\"Action\"]\n"
    "    arrow = \"-->\"\n"
    "    cur = row[\"Current Calls/Month\"]\n"
    "    opt = row[\"Optimal Calls/Month\"]\n"
    "    net = row[\"Net Monthly Impact/Doc ($)\"]\n"
    "    print(f\"  {row['Segment']:20s} [{action:8s}]  \"\n"
    "          f\"{cur:.1f} {arrow} {opt} calls/mo  |  \"\n"
    "          f\"Net: ${net:+.0f}/doc/mo\")"
))

C.append(md_cell("---\n## Summary\n\n"
    "| Model | AIC | Key Insight |\n"
    "|-------|-----|-------------|\n"
    "| Baseline OLS | ~53,690 | Poor fit; curvature in residuals |\n"
    "| MM Response Curve | ~51,645 | 2,045-pt improvement; interpretable Vmax/Km |\n"
    "| Mixed LM | ~4,628 (log-Rx scale) | Correct SE via territory random effects |\n\n"
    "**Business recommendation:** Reallocate call resources from GPs (at optimum) "
    "toward Cardiologists and Endocrinologists (currently under-called), "
    "projected net gain of **+$247–$315 per doctor per month** at current cost assumptions.\n\n"
    "**Key limitations:**\n"
    "- Call frequency is not randomly assigned (endogeneity risk)\n"
    "- No temporal carry-over effects modeled\n"
    "- Simulated data — requires validation on real prescriber data before production use"))

# ── Write notebook ─────────────────────────────────────────────────────────
out_path = pathlib.Path("notebooks/analysis.ipynb")
out_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"Notebook written to {out_path}")
print(f"  {len(nb['cells'])} cells")
